In [87]:
import csv 
import numpy as np

In [115]:
import numpy as np
import csv

with open(r"C:\Users\dc\Downloads\terrorismData.csv") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)
    df = list(data)


    
ans =[]
for row in df:
    ans.append([row['Day'], row['Month'],row['Year']])

ans=np.array(ans)
cnt=0
for row in ans:
    if int(float(row[0])) > 0 and int(float(row[1]))==1 and int(float(row[2]))==2010:
        cnt+=1
print(cnt)

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 6235: character maps to <undefined>

In [88]:
with open(r"C:\Users\dc\Downloads\terrorismData.csv", encoding="utf8") as f:
    data = csv.DictReader(f,skipinitialspace=True)
    df = list(data)

In [89]:
df

[{'Year': '1970',
  'Month': '7',
  'Day': '2',
  'Country': 'Dominican Republic',
  'State': '',
  'Region': 'Central America & Caribbean',
  'City': 'Santo Domingo',
  'Latitude': '18.456792',
  'Longitude': '-69.951164',
  'AttackType': 'Assassination',
  'Killed': '1.0',
  'Wounded': '0.0',
  'Target': 'Julio Guzman',
  'Summary': '',
  'Group': 'MANO-D',
  'Target_type': 'Private Citizens & Property',
  'Weapon_type': 'Unknown'},
 {'Year': '1970',
  'Month': '0',
  'Day': '0',
  'Country': 'Mexico',
  'State': 'Federal',
  'Region': 'North America',
  'City': 'Mexico city',
  'Latitude': '19.371887',
  'Longitude': '-99.086624',
  'AttackType': 'Hostage Taking (Kidnapping)',
  'Killed': '0.0',
  'Wounded': '0.0',
  'Target': 'Nadine Chaval, daughter',
  'Summary': '',
  'Group': '23rd of September Communist League',
  'Target_type': 'Government (Diplomatic)',
  'Weapon_type': 'Unknown'},
 {'Year': '1970',
  'Month': '1',
  'Day': '0',
  'Country': 'Philippines',
  'State': 'Tarlac

In [90]:
ans =[]
for row in df:
    ans.append([row['Day'], row['Month'],row['Year']])

In [91]:
ans=np.array(ans)

In [92]:
ans

array([['2', '7', '1970'],
       ['0', '0', '1970'],
       ['0', '1', '1970'],
       ...,
       ['31', '12', '2017'],
       ['31', '12', '2017'],
       ['31', '12', '2017']], dtype='<U4')

In [93]:
type(ans)

numpy.ndarray

In [94]:
print(ans)

[['2' '7' '1970']
 ['0' '0' '1970']
 ['0' '1' '1970']
 ...
 ['31' '12' '2017']
 ['31' '12' '2017']
 ['31' '12' '2017']]


In [97]:
arr = ans[ans[2] ==2010]

C:\Users\dc\AppData\Local\Temp\ipykernel_13144\470778007.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  arr = ans[ans[2] ==2010]


In [100]:
print(arr)

[]


In [109]:
cnt=0
for row in ans:
    if int(float(row[0])) > 0 and int(float(row[1]))==1 and int(float(row[2]))==2010:
        cnt+=1
print(cnt)

271


In [41]:
import numpy as np
import csv


days = [1,1,2,3,4,5,6]
months=[1,1,1,2,2,2,1]
year = [2010,2010,2010,2012,2025,2010,2012]


np_day = np.array(days, dtype=float)
print(np_day)
np_month = np.array(months, dtype=float)
print(np_month)
np_year = np.array(year, dtype=float)
print(np_year)

print()
print()
print()

np_day = np_day[np_month==1]
print(np_day)
print(np_month)
print(np_year)
print()

np_year = np_year[np_month==1]
print(np_day)
print(np_month)
print(np_year)
print()

np_day = np_day[np_year==2010]
print(np_day)
print(np_month)
print(np_year)
print()


#print(len(np_day[np_day!=0]))

[1. 1. 2. 3. 4. 5. 6.]
[1. 1. 1. 2. 2. 2. 1.]
[2010. 2010. 2010. 2012. 2025. 2010. 2012.]



[1. 1. 2. 6.]
[1. 1. 1. 2. 2. 2. 1.]
[2010. 2010. 2010. 2012. 2025. 2010. 2012.]

[1. 1. 2. 6.]
[1. 1. 1. 2. 2. 2. 1.]
[2010. 2010. 2010. 2012.]

[1. 1. 2.]
[1. 1. 1. 2. 2. 2. 1.]
[2010. 2010. 2010. 2012.]

